### ISSUE TITLE
what am i doing wrong?

### ISSUE THREAD

**Issue by rm-rf-robert** [CalebEverett/arloader#30]
```
freshskates@not-localhost:/mnt/c/Users/freshskates/Desktop/Languages/Blockchain/test/exclusives$ arloader upload-nfts ./*.gif --with-sol --sol-keypair-path ~/.config/solana/test.json --ar-default-keypair


Uploading assets...

Uploading 1 files with 263 KB of data in 1 bundle transactions...

StatusCodeNotOk

Uploaded 0 KB in 0 files in 0 bundle transaction(s). Run `arloader update-status ./arloader_MA0-zRzXZQ4/assets/` to update statuses.


Uploading manifest for images...

No bundle statuses found in ./arloader_MA0-zRzXZQ4/assets/
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/freshskates/.cargo/registry/src/github.com-1ecc6299db9ec823/arloader-0.1.63/src/commands.rs:802:6
stack backtrace:
   0:     0x555bd019dc8d - std::backtrace_rs::backtrace::libunwind::trace::hee56aa883c63acb5
                               at /rustc/89b9f7b284aacc5f8613438b80e4dd7bdd10549e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x555bd019dc8d - std::backtrace_rs::backtrace::trace_unsynchronized::he7cac0994dc78c4c
                               at /rustc/89b9f7b284aacc5f8613438b80e4dd7bdd10549e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x555bd019dc8d - std::sys_common::backtrace::_print_fmt::hdc12a102f76753bd
                               at /rustc/89b9f7b284aacc5f8613438b80e4dd7bdd10549e/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x555bd019dc8d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf7faa06c147903ce
                               at /rustc/89b9f7b284aacc5f8613438b80e4dd7bdd10549e/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x555bcffac2bc - core::fmt::write::h66e8369cb6d370fa
                               at /rustc/89b9f7b284aacc5f8613438b80e4dd7bdd10549e/library/core/src/fmt/mod.rs:1168:17
   5:     0x555bd0177d54 - std::io::Write::write_fmt::h74797452eefbc651
                               at /rustc/89b9f7b284aacc5f8613438b80e4dd7bdd10549e/library/std/src/io/mod.rs:1653:15
   6:     0x555bd019ef35 - std::sys_common::backtrace::_print::h82e64c28f7109909
                               at /rustc/89b9f7b284aacc5f8613438b80e4dd7bdd10549e/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x555bd019ef35 - std::sys_common::backtrace::print::hef2d97a7e889059a
                               at /rustc/89b9f7b284aacc5f8613438b80e4dd7bdd10549e/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x555bd019ef35 - std::panicking::default_hook::{{closure}}::hc4f2f631c593350e
                               at /rustc/89b9f7b284aacc5f8613438b80e4dd7bdd10549e/library/std/src/panicking.rs:211:50
   9:     0x555bd019fdca - std::panicking::default_hook::he01061695065e502
                               at /rustc/89b9f7b284aacc5f8613438b80e4dd7bdd10549e/library/std/src/panicking.rs:228:9
  10:     0x555bd019fdca - std::panicking::rust_panic_with_hook::h3ad36e38c2432eec
                               at /rustc/89b9f7b284aacc5f8613438b80e4dd7bdd10549e/library/std/src/panicking.rs:606:17
  11:     0x555bd019f886 - std::panicking::begin_panic_handler::{{closure}}::hc909e1e15fb3ebac
                               at /rustc/89b9f7b284aacc5f8613438b80e4dd7bdd10549e/library/std/src/panicking.rs:500:13
  12:     0x555bd019f826 - std::sys_common::backtrace::__rust_end_short_backtrace::hfcf0febb37587b3d
                               at /rustc/89b9f7b284aacc5f8613438b80e4dd7bdd10549e/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x555bd019f7e2 - rust_begin_unwind
                               at /rustc/89b9f7b284aacc5f8613438b80e4dd7bdd10549e/library/std/src/panicking.rs:498:5
  14:     0x555bcfe2a0f0 - core::panicking::panic_fmt::h6a50bf58d4eb52b4
                               at /rustc/89b9f7b284aacc5f8613438b80e4dd7bdd10549e/library/core/src/panicking.rs:110:14
  15:     0x555bcfe2a24c - core::panicking::panic::h2379521af04ff957
                               at /rustc/89b9f7b284aacc5f8613438b80e4dd7bdd10549e/library/core/src/panicking.rs:48:5
  16:     0x555bcfe68cbc - arloader::commands::command_upload_nfts::{{closure}}::hb74ad99e1a56c002
  17:     0x555bcfe50653 - arloader::main::{{closure}}::hd22cca23b22f2d15
  18:     0x555bcff038d4 - tokio::runtime::Runtime::block_on::h93430bb1a19d2393
  19:     0x555bcff46d03 - arloader::main::h0920b29802615e26
  20:     0x555bcfee68e3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8613cfdecd68f448
  21:     0x555bcff46327 - main
  22:     0x7f81c37e70b3 - __libc_start_main
  23:     0x555bcfe3682e - _start
  24:                0x0 - <unknown>
  
```

what could I be doing wrong?

**Comment by rm-rf-robert** [comment]
I have solana balance, and i have two files in the dir

0.gif
0.json

**Comment by CalebEverett** [comment]
Try a higher reward multiplier and/or a bigger bundle, i.e. more files to get the reward higher

**Comment by CalebEverett** [comment]
Actually are you on wsl2 ?

**Comment by rm-rf-robert** [comment]
![image](https://user-images.githubusercontent.com/67438520/173991991-3689c395-9128-4232-8fbc-cba409c45938.png)

yea

**Comment by CalebEverett** [comment]
This might not be it, but can you move the Linux binary into wsl and call from there instead of windows dir?

**Comment by rm-rf-robert** [comment]
![image](https://user-images.githubusercontent.com/67438520/173992860-3a273abe-4147-430c-973a-5fe2ea409307.png)

Ok will try that, also just wanted to point out the log lines:

```
Retrying Solana transaction (1 of 10)...
```

Not sure if that gives hint towards the issue, but also ill give what you mentioned a try

**Comment by CalebEverett** [comment]
Ok try the higher reward multiplier too

**Comment by CalebEverett** [comment]
The solana retry will retry 10 times. It timed out if not confirem in I think 5 seconds, but then tries again. Up to 10 times.

**Comment by rm-rf-robert** [comment]
```
{
  "name": "test123",
  "symbol": "SB",
  "description": "lorem ipsum",
  "seller_fee_basis_points": 800,
  "image": "0.gif",
  "external_url": "",
  "edition": 0,
  "attributes": [
    {
      "trait_type": "test",
      "value": "test123"
    }
  ],
  "properties": {
    "files": [
      {
        "uri": "0.gif",
        "type": "image/gif"
      }
    ],
    "category": "gif",
    "creators": [
      {
        "address": "wallet address goes here",
        "share": 50
      },
      {
        "address": "wallet address goes here",
        "share": 50
      }
    ]
  }
}
```

does this look right for a json?

this goes along with the 0.gif file, but could it be the json syntax? it used to work for me months ago, but maybe I messed something up this time

**Comment by CalebEverett** [comment]
There are some examples  files here you could use. https://github.com/CalebEverett/arloader/tree/master/tests/fixtures

**Comment by HZfive** [comment]
hi @CalebEverett  
`arloader estimate *.json -r 20`
`error: Invalid value for '--reward-multiplier <REWARD_MULT>': Multiplier must be a float between 0 and 3.`
`arloader 0.1.63`

examples:
`arloader estimate *.json -r 10`
`The price to upload 999 files with 946017 total bytes in 1 transaction(s) is 2019429120 winstons ($0.0274).`
`arloader upload *.json -r 10  --ar-keypair-path ~/xxx/SO7gY80bAH8f_osfXiuUsIqFZSb3OH2q2-4vMv43ogg.json`
`Uploading 999 files with 946 KB of data in 1 bundle transactions...`

` bundle txid                                   items      KB  status       confirms`
`------------------------------------------------------------------------------------`
` zXg4MovG05j68vgxY40evcsW-7yOvNgqbcdzSA3wqto     999     946  Submitted           0`

`Uploaded 946 KB in 999 files in 1 bundle transactions. Run `arloader update-status arloader_iAh8iXPbmTo` to update statuses.`
`arloader update-status arloader_iAh8iXPbmTo`
` bundle txid                                   items      KB  status       confirms`
`------------------------------------------------------------------------------------
` zXg4MovG05j68vgxY40evcsW-7yOvNgqbcdzSA3wqto     999     946  NotFound            0`

`arloader estimate *.json -r 20`
`error: Invalid value for '--reward-multiplier <REWARD_MULT>': Multiplier must be a float between 0 and 3.`

`arloader estimate *.json -r 10`
`The price to upload 1000 files with 4334786 total bytes in 1 transaction(s) is 8562543360 winstons ($0.1166).`
`arloader upload *.json -r 10  --ar-keypair-path ~/xxx/SO7gY80bAH8f_osfXiuUsIqFZSb3OH2q2-4vMv43ogg.json`
Uploading 1000 files with 4334 KB of data in 1 bundle transactions...`

` bundle txid                                   items      KB  status       confirms`
`------------------------------------------------------------------------------------`
` i6BYChxhKiuSRwRVSc_UFzjYUeLCKlrCxPQ1khZW7dQ    1000    4334  Submitted           0`

`Uploaded 4334 KB in 1000 files in 1 bundle transactions. Run `arloader update-status arloader_VAQ0q4hHQ9c` to update statuses.`
` bundle txid                                   items      KB  status       confirms`
`------------------------------------------------------------------------------------`
` i6BYChxhKiuSRwRVSc_UFzjYUeLCKlrCxPQ1khZW7dQ    1000    4334  Confirmed           4`

Can the  '--reward-multiplier <REWARD_MULT>' go up ?
and why this one work:

` arloader upload ./assets/0.json -o json --sol-keypair-path solana.json --with-sol --ar-default-keypair  --reward-multiplier 6` 
` Uploading 1 files with 0 KB of data in 1 bundle transactions...` 

` arloader update-status ./assets/arloader_SKnmekBC4Zk` 
`  bundle txid                                   items      KB  status       confirms` 
` ------------------------------------------------------------------------------------` 
`  KXZkrH_3n2I7z1iyIGARY7RhBpILDKU9UA1kykEqt2Q       1       0  Pending             0` 

` arloader update-status ./assets/arloader_SKnmekBC4Zk` 
`  bundle txid                                   items      KB  status       confirms` 
` ------------------------------------------------------------------------------------` 
`  KXZkrH_3n2I7z1iyIGARY7RhBpILDKU9UA1kykEqt2Q       1       0  Confirmed           1` 

just upload one file with 0kb and ' --reward-multiplier 6'  is fine, but 999 with 946 KB  ' --reward-multiplier 10'
