### ISSUE TITLE
get-status JSON output panics

### ISSUE THREAD

**Issue by dmichael** [CalebEverett/arloader#31]
* Installed through cargo on macOS. 
* Attempting to get status of a tx with JSON output panics
* This tx is pending at the time
```
arloader get-status Y-sqEXggvUCoGaeYJfpGKg7LLNCORBiAGBKyG5aYIhM --output json
thread 'main' panicked at 'byte index 32 is out of bounds of ``', library/core/src/str/mod.rs:107:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by CalebEverett** [comment]
I'll check this, sorry about the panic. Can you try moving the output flag to right after arloader?

**Comment by dmichael** [comment]
> I'll check this, sorry about the panic. Can you try moving the output flag to right after arloader?

Same
```
arloader --output json get-status uPXb9i3CcCXBrWI6m_2nDfw9Vkl1F5syOeuXzKCLT68
thread 'main' panicked at 'byte index 32 is out of bounds of ``', library/core/src/str/mod.rs:107:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```
